# Environment will come from runtime argument

dev.OrgUrl=https://aegislimiteddev.service-now.com
stg.OrgUrl=https://aegisdev.service-now.com
prd.OrgUrl=https://aegislimited.service-now.com

restEndPoint=/api/now/table/u_member_services

dev.userName=member_services_svc
dev.password=C%1t0f\&BrcE6fBxkEFR)

stg.userName=member_services_svc
stg.password=

prd.userName=member_services_svc
prd.password=

# DB Config
dev.db.url=jdbc:oracle:thin:@localhost:1521:xe
dev.db.user=system
dev.db.password=system

stg.db.url=
stg.db.user=
stg.db.password=

prd.db.url=
prd.db.user=
prd.db.password=

# Timeouts
http.connect.timeout=5000
http.read.timeout=10000

# Scheduler
scheduler.interval.ms=120000